/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

char findTheDifference(char* s, char* t) {
#if 0
    int i, n[26] = { 0 };
    while (*s) {
        n[*s - 'a'] ++;
        n[*t - 'a'] --;
        s ++;
        t ++;
    }
    n[*t - 'a'] --;
    for (i = 0; i < 26; i ++) {
        if (n[i]) return i + 'a';
    }
    return 0;
#else
    char c = t[0];
    t ++;
    while (*s) {
        c = c ^ *s ^ *t;
        s ++;
        t ++;
    }
    return c;
#endif
}


/*
Difficulty:Easy
Total Accepted:77.4K
Total Submissions:152.9K


Companies Google
Related Topics Hash Table Bit Manipulation
Similar Questions 
                
                  
                    Single Number
*/
